dataPath: "/data"
receiver:
  listenOn:          "0.0.0.0:2525"
  domain:            "localhost"
  readTimeout:       20
  writeTimeout:      20
  maxMessageBytes:   1048576
  maxRecipients:     50
  allowInsecureAuth: true