[supervisord]
user             = root
nodaemon         = true
logfile          = /dev/null
logfile_maxbytes = 0

[inet_http_server]
port=0.0.0.0:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:arquebuse-mail]
autostart       = true
autorestart     = true
command         = arquebuse-mail
startsecs       = 1

[program:arquebuse-api]
autostart       = true
autorestart     = true
command         = arquebuse-api
startsecs       = 1

[program:nginx]
autostart       = true
autorestart     = true
command         = nginx -g 'daemon off;'
startsecs       = 1